<a href="https://colab.research.google.com/github/dinithprimal/DeepLearning_Tutorials/blob/main/EX17_Word_Embedding_using_Keras_Embedding_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [12]:
reviews = ['nice food',
           'amazing restaurent',
           'too good',
           'just love it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor services',
           'poor quality',
           'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

## One Hot Encoding

In [13]:
one_hot('amazing restautrent', 30)

[15, 15]

In [14]:
vocab_size = 30

encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[20, 10], [15, 12], [6, 27], [22, 6, 22], [22, 26, 10], [22, 10], [26, 26, 23], [8, 19], [8, 11], [14, 3]]


In [24]:
max_length = 3

padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[20 10  0]
 [15 12  0]
 [ 6 27  0]
 [22  6 22]
 [22 26 10]
 [22 10  0]
 [26 26 23]
 [ 8 19  0]
 [ 8 11  0]
 [14  3  0]]


### Embedded Vector

In [25]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [26]:
X = padded_reviews
y = sentiment

In [27]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_3 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [28]:
model.fit(X, y, epochs=50, verbose=0)

In [29]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [30]:
# Word "nice" weights
weights[20]

array([-0.07836847,  0.03326798, -0.07038449, -0.04835618], dtype=float32)

In [31]:
# Word "amazing" weights
weights[15]

array([-0.06122058,  0.0786567 , -0.08000238, -0.06264515], dtype=float32)

In [32]:
# Word "poor" weights
weights[8]

array([ 0.05245402, -0.05716141,  0.05796015,  0.0657612 ], dtype=float32)