<a href="https://colab.research.google.com/github/dinithprimal/DeepLearning_Tutorials/blob/main/EX19_Tensoflow_Input_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

## Simple Tensorflow dataset

In [ ]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [ ]:
for sales in tf_dataset:
  print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [ ]:
for sales in tf_dataset:
  print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [ ]:
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
-108
31
-1
32
34
31


In [ ]:
for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-108


In [ ]:
tf_dataset = tf_dataset.filter(lambda x: x>0)

for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
31
32
34
31


In [ ]:
tf_dataset = tf_dataset.map(lambda x: x*360)

for sales in tf_dataset.as_numpy_iterator():
  print(sales)

7560
7920
11160
11520
12240
11160


In [ ]:
tf_dataset = tf_dataset.shuffle(3)

for sales in tf_dataset.as_numpy_iterator():
  print(sales)

7920
11160
7560
11160
11520
12240


In [ ]:
for sales_batch in tf_dataset.batch(2):
  print(sales_batch.numpy())

[11160  7560]
[11520 11160]
[ 7920 12240]


In [ ]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

# Input Data Pipelining
tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*360).shuffle(3).batch(2)

for sales_batch in tf_dataset.as_numpy_iterator():
  print(sales_batch)

[11160  7560]
[12240  7920]
[11520 11160]


In [16]:
images_ds = tf.data.Dataset.list_files('Images/*/*', shuffle=False)

for file in images_ds.take(3):
  print(file.numpy())

b'Images/Cat/01h84ks8b3kn95ybj78q.jpg'
b'Images/Cat/27gingercat0611.jpg'
b'Images/Cat/437FC169-B9A1-4D56-AD1C2C5B95435970_source.jpg'


In [17]:
images_ds = images_ds.shuffle(200)

for file in images_ds.take(3):
  print(file.numpy())

b'Images/Dog/7f6a5603-e95a-4364-899c-6b60ab293c10-VPC_BOBI_THE_OLDEST_DOG_2023.00_00_01_15.Still001.jpg'
b'Images/Cat/01h84ks8b3kn95ybj78q.jpg'
b'Images/Cat/tabby_cat_in_the_garden.jpg'


In [18]:
class_names = ['cat', 'dog']

In [19]:
image_count = len(images_ds)
image_count

29

In [20]:
train_size = int(image_count*0.8)

train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [21]:
len(train_ds)

23

In [22]:
len(test_ds)

6

In [25]:
s = 'Images/Cat/01h84ks8b3kn95ybj78q.jpg'

s.split('/')[-2]

'Cat'

In [28]:
def get_label(file_path):
  import os
  return tf.strings.split(file_path, os.path.sep)[-2] #file_path.split('/')[-2]

In [30]:
def process_image(file_path):
  label = get_label(file_path)

  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img, [128, 128])

  return img, label

In [27]:
for t in train_ds.take(4):
  print(t.numpy())

b'Images/Cat/98637594.jpg'
b'Images/Dog/dog-4615198_1280_1701927561029_1701927572424.jpg'
b'Images/Cat/6Cat-Alamy.jpg'
b'Images/Cat/reddit-cats-judging-looks-00.jpg'


In [29]:
for label in train_ds.map(get_label):
  print(label)

tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)
tf.Tensor(b'Cat', shape=(), dtype=string)
tf.Tensor(b'Dog', shape=(), dtype=string)


In [35]:
train_ds = train_ds.map(process_image)

for img, label in train_ds.take(3):
  print("Image: ", img)
  print("Label: ", label)

Image:  tf.Tensor(
[[[ 49.1875    39.8125    44.695312]
  [ 75.390625  43.79297   60.0625  ]
  [ 87.85156   56.07422   71.0625  ]
  ...
  [241.30078  193.125    190.875   ]
  [252.35547  205.875    208.875   ]
  [252.88281  207.1875   207.33984 ]]

 [[ 44.51953   41.64453   42.64453 ]
  [ 65.81641   60.691406  61.128906]
  [120.57031  108.33984  103.69531 ]
  ...
  [235.77734  172.90234  167.90234 ]
  [253.1211   202.36719  200.49219 ]
  [253.01953  203.10547  207.01953 ]]

 [[ 42.82422   41.82422   39.82422 ]
  [ 44.695312  45.285156  38.492188]
  [ 87.41797   86.99609   77.125   ]
  ...
  [216.2539   149.2461   130.08203 ]
  [232.       161.35547  147.125   ]
  [234.97266  171.13672  162.36328 ]]

 ...

 [[123.23828  120.86328  108.05078 ]
  [124.82031  118.90234  102.94531 ]
  [116.375    114.25781   99.44141 ]
  ...
  [209.6914   195.6914   168.7539  ]
  [201.       186.       163.      ]
  [200.82422  185.82422  162.82422 ]]

 [[137.14062  132.76953  118.22656 ]
  [132.       127.

In [34]:
def scale(image, label):
  return image/255.0, label

In [36]:
train_ds = train_ds.map(scale)

for image, label in train_ds.take(3):
  print("****Image: ", image.numpy()[0][0])
  print("****Label: ", label.numpy())

****Image:  [0.91764706 0.96862745 0.9411765 ]
****Label:  b'Cat'
****Image:  [0.47487745 0.30232844 0.15669423]
****Label:  b'Cat'
****Image:  [0.39607844 0.35686275 0.2509804 ]
****Label:  b'Dog'
