<a href="https://colab.research.google.com/github/dinithprimal/DeepLearning_Tutorials/blob/main/EX22_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip3 install tensorflow_text

In [4]:
import tensorflow_hub as hub
import tensorflow_text as text

In [5]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [6]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [7]:
text_test = ['nice movie indeed', 'I love Python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [8]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [9]:
text_preprocessed['input_word_ids']

# CLS nice moive indeed SEP
# CLS I love Python programming SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [12]:
bert_model = hub.KerasLayer(encoder_url)
bert_result = bert_model(text_preprocessed)
bert_result.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'default', 'pooled_output'])

In [13]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.21411921,  0.49769515, ...,  0.24465193,
        -0.47334474,  0.8175871 ],
       [-0.91712314, -0.47935188, -0.78656995, ..., -0.61751765,
        -0.7102687 ,  0.921843  ]], dtype=float32)>

In [14]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567815,  0.14476833, ..., -0.09677089,
          0.08722138,  0.07711098],
        [ 0.17839392, -0.19006105,  0.50349474, ..., -0.05869799,
          0.32717094, -0.15578488],
        [ 0.18701468, -0.43388787, -0.48875138, ..., -0.15502772,
          0.00145124, -0.24470966],
        ...,
        [ 0.12083106,  0.12884258,  0.46453524, ...,  0.07375515,
          0.17441994,  0.16522008],
        [ 0.07967864, -0.01190711,  0.50225407, ...,  0.13777758,
          0.21002217,  0.00624588],
        [-0.07212694, -0.2830348 ,  0.59033334, ...,  0.47551954,
          0.16668473, -0.08920345]],

       [[-0.07900596,  0.36335123, -0.2110157 , ..., -0.17183766,
          0.1629974 ,  0.6724269 ],
        [ 0.27883503,  0.43716323, -0.35764694, ..., -0.0446365 ,
          0.3831516 ,  0.5887988 ],
        [ 1.203767  ,  1.0727018 ,  0.4840876 , ...,  0.24920997,
          0.40730938,  0.404818  ],
        ...,

In [16]:
bert_result['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567815,  0.14476833, ..., -0.09677089,
          0.08722138,  0.07711098],
        [ 0.17839392, -0.19006105,  0.50349474, ..., -0.05869799,
          0.32717094, -0.15578488],
        [ 0.18701468, -0.43388787, -0.48875138, ..., -0.15502772,
          0.00145124, -0.24470966],
        ...,
        [ 0.12083106,  0.12884258,  0.46453524, ...,  0.07375515,
          0.17441994,  0.16522008],
        [ 0.07967864, -0.01190711,  0.50225407, ...,  0.13777758,
          0.21002217,  0.00624588],
        [-0.07212694, -0.2830348 ,  0.59033334, ...,  0.47551954,
          0.16668473, -0.08920345]],

       [[-0.07900596,  0.36335123, -0.2110157 , ..., -0.17183766,
          0.1629974 ,  0.6724269 ],
        [ 0.27883503,  0.43716323, -0.35764694, ..., -0.0446365 ,
          0.3831516 ,  0.5887988 ],
        [ 1.203767  ,  1.0727018 ,  0.4840876 , ...,  0.24920997,
          0.40730938,  0.404818  ],
        ...,